### ISSUE TITLE
Does not work on windows.

### ISSUE THREAD

**Issue by BringerOD** [m3talstorm/foe-bot#1]
$ python main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from models.account import Account
  File "C:\src\Misc\foe-bot\foe\models\account.py", line 128

    ^
SyntaxError: EOF while scanning triple-quoted string literal

**Comment by m3talstorm** [comment]
Sorry for the late reply, must have missed the Github notification/email. 

I'll have a look at this shortly, feel free to submit a PR if you have a fix for it.

**Comment by m3talstorm** [comment]
Should be fixed by #2
