### ISSUE TITLE
Will the bot continuously visit taverns and aid friends / neighbours?

### ISSUE THREAD

**Issue by LordMike** [m3talstorm/foe-bot#12]
I've left it running for a while a few times, but every time I restart it, it finds a bunch of friends to aid or taverns to visit. It's like it does this once and then not again..

Maybe what I'm seeing is batches of friends/taverns coming between full update cycles (I imagine they all have the same frequency,

**Comment by m3talstorm** [comment]
Yes the bot should collect from your tavern and should visit/aid other players periodically (every few mins)
