### ISSUE TITLE
Make the bot not bannable

### ISSUE THREAD

**Issue by ecavicc** [m3talstorm/foe-bot#16]
I've been banned for two hours some minutes after closing the bot, which I had been using for just some seconds to see if it worked. Any way the bot could be be stealthier, maybe making it act more human-like? Works great, though.

**Comment by m3talstorm** [comment]
I'd be very surprised if 'some seconds' worth of usage would be enough for any countermeasures to pick up on it.

Unless some request headers have changed and they are basing it on that.

**Comment by ecavicc** [comment]
It was less than a minute... Anyway, it was kind of random, probably, since I've been letting it run for quite a while without any problems. No idea what happened.

**Comment by m3talstorm** [comment]
So 'some seconds' was not really true ;) I expect the ban was applied when you next logged in, and that's why you saw it.

**Comment by ecavicc** [comment]
Hey, if it's not a minute it still is some seconds ;) Keep up the good work.
