### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by bombcheck** [m3talstorm/foe-bot#6]
Hi there,

just tried it (using python 3.4). Results:
#> python3.4 main.py
  File "main.py", line 38
    print "Players: %s" % (len(account.players))
                      ^
SyntaxError: invalid syntax

Any ideas?

**Comment by bombcheck** [comment]
Ah, seems the bot does not work well with python 3. Some changes in the print-statement.
Using python 2.7 now, works fine!

**Comment by m3talstorm** [comment]
@bombcheck Ye the bot just works with Python 2.7 at the moment, I don't have any plans to port it over.
